# Generated by Django 2.2 on 2019-04-20 05:53

from django.db import migrations, models
import django.utils.timezone
from django.utils import timezone
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2019-04-04 06:00:00.000000-08:00'), #remove previous not worked migration and add this string in datetime field, works for me
            preserve_default=False,
        ),
    ]
