# Generated by Django 2.2 on 2019-04-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_cat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cat',
            table='cat',
        ),
    ]
