# Generated by Django 2.2 on 2019-04-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_ecat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datetest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.DateField(blank=True)),
            ],
            options={
                'db_table': 'datetest',
            },
        ),
    ]
